In [ ]:
LIST KE ANDAR INSERTION SAB KR SAKTE HAI NUMPY ARRAY MAI NAHI
NUMPY ARRAY MULIDIMENSIONAL BHI BANA SAKTE HAI LIST NAH
LIST KA COMPUTAION SLOW HAI AS COMPARED TO NUMPY

In [ ]:
SIMILARITAY IN NUMPY ARRAY AND LIST
1. BOTH STORE DATA    2. SLICING   3. CAN BE INDEXED   4. MUTABLE

In [ ]:
DIFFERENCE IN LIST AND NUMPY ARRAY:
1.LIST: CAN CONTAIN ELEMENT OF DIFFERENT DATA TYPE
2. ARRAY: CONTAIN ELEMENT OF SIMILAR DATA TYPE    
3. operation in array is easier than list    

In [1]:
l1=[1,2,3,4,"vikas",12.3]
l1

[1, 2, 3, 4, 'vikas', 12.3]

In [80]:
v1=np.array([1,2,"vikas",34.0])
v1 
# here it is considering all the element as string


array(['1', '2', 'vikas', '34.0'], dtype='<U11')

In [5]:
import numpy as np
b1=np.array(l1)
b1

NameError: name 'l1' is not defined

In [41]:
v2=np.array([1,2,3,4,5,6])
v2/2
# but this operation is not possible in list

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

In [2]:
import numpy as np

In [42]:
v2*2   # same function works differenlly with list

array([ 2,  4,  6,  8, 10, 12])

In [43]:
s1=[1,2,3,4]
print(s1*2)

[1, 2, 3, 4, 1, 2, 3, 4]


In [2]:
#1D ARRAY CREATION
a=numpy.array([1,2,3,4,5])

In [3]:
a

array([1, 2, 3, 4, 5])

In [4]:
a.shape

(5,)

In [5]:
a

array([1, 2, 3, 4, 5])

In [3]:
a1=np.array([[1,2,3],[8,9,10]])
a1

array([[ 1,  2,  3],
       [ 8,  9, 10]])

In [4]:
a1.shape

(2, 3)

In [5]:
a2=np.array([[1,2,3],[7,8,9],[2,4,6]])
a2

array([[1, 2, 3],
       [7, 8, 9],
       [2, 4, 6]])

In [9]:
a2.reshape(1,9)   #re arrange into new array dimension
# 3X3 can be changed into 1,9 as element is 9 in both case

array([[1, 2, 3, 7, 8, 9, 2, 4, 6]])

In [6]:
m=np.arange(15)   # give sequence of first 15 integers
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [7]:
print(type(m))

<class 'numpy.ndarray'>


In [14]:

m=np.arange(10).reshape(2,5)
m

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
m.size



10

In [24]:
print(m.min())  # minimum value in a array
print(m.max())  # maximum value in a array

0
9


In [25]:
n1=np.array([[1,2],[3,4],[5,6]],dtype='float64')   # we can mention the data type explicitly
n1

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [29]:
n1.size

6

In [31]:
n1.ravel()    # ravel operation can convert one numpy array into single row

array([1., 2., 3., 4., 5., 6.])

In [33]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [38]:
np.ones((2,3),dtype='int32')

array([[1, 1, 1],
       [1, 1, 1]])

In [39]:
#MULTI DIMENSIONAL

In [41]:
j=np.ones((2,3,4))   # 3 dimension data
j

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [42]:
j.shape

(2, 3, 4)

In [43]:
j.ndim  # 3 dimensional

3

In [44]:
np.empty((5,5))   #ny junk values

array([[3.95e-322, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000],
       [0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000, 0.00e+000]])

In [46]:
# start,end,jump,skip

np.arange(10,30,5)

array([10, 15, 20, 25])

In [47]:
np.arange(10,70,6)

array([10, 16, 22, 28, 34, 40, 46, 52, 58, 64])

In [49]:
import numpy as np
np.linspace(0,5,10)   # print number between 0-5 with 10 divisions

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [52]:
a=np.array([10,20,30,40])
b=np.array([1,2,3,4,])
print(a)
print(b)

[10 20 30 40]
[1 2 3 4]


In [53]:
c=a-b # perform mathematical operations on array but they should have same array size
c

array([ 9, 18, 27, 36])

In [54]:
a**2   # squaring 

array([ 100,  400,  900, 1600], dtype=int32)

In [55]:
# RANDOM FUNCTION
n=np.random.random((2,3))   # random is package and inside random is class inside that package
n

array([[0.70340953, 0.09105521, 0.40462386],
       [0.87740237, 0.71741414, 0.09537268]])

In [58]:
v=np.array([1,"vikas",3,4])
v[1]

'vikas'

UNIVERSAL FUNCTION in numpy which can be appllied on the array

In [59]:
b=np.arange(4)

In [60]:
np.exp(b)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [61]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [64]:
c=np.array((2,1,4))
d=np.array((3,4,5))
np.add(c,d)

array([5, 5, 9])

INDEXING/SLICING/ITERATING

In [6]:
#same like list
d1=np.array([1,3,5,7,9,11,13])
d1[0:6:2]    # just like list slicing


array([1, 5, 9])

In [7]:
d1[2]

5

In [71]:
#ANOTHER WAY IS BY USING SLICE FUNCTION
S=slice(0,6,2)
print(d1[S])

[1 5 9]


In [75]:
d2=np.array([np.nan,1,2,3,np.nan])   # whenever data is missing dont use '0' instead used np.nan.as we dont know anythig about data
print(d2[~np.isnan(d2)])

[1. 2. 3.]


# RANDOM NUMBER

In [76]:
# it can generate random number inside random pakcage
# There is one more function in random package i.e rand which will also print random number but with uniform distribution

In [77]:
np.random.rand(2,2)   #  -> uniform distribution

array([[0.87833683, 0.4611107 ],
       [0.89795872, 0.89887473]])

In [78]:
np.random.randn(2,3)   # -> normal distribution

array([[ 1.1176958 , -0.11412607,  0.22960084],
       [ 1.30822699, -1.06221403,  1.1671749 ]])

Slicing/Indexing in 2d

In [9]:
a1=[1,2,3,4]
b1=[2,3,4,5]
c1=[5,6,7,8]
arr=np.array([a1,b1,c1])

In [10]:
arr   # this is 2D

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [5, 6, 7, 8]])

In [11]:
arr.shape

(3, 4)

In [12]:
arr[:,:]   

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [5, 6, 7, 8]])

In [15]:
arr[:,1:3]   #(row start:row end,col start:col end) # indexing starts with 0

array([[2, 3],
       [3, 4],
       [6, 7]])

In [17]:
arr[1:3,1:3]  # aagar 2nd col lena hai tohe  3 likhenge kyuki 3-1 consider hota hai row and col end mai

array([[3, 4],
       [6, 7]])

Arr is reference type means any chaenge in arr will be reflected in the array

In [30]:
arr1=np.array([1,2,3,5,6,7,8,9])

In [31]:
arr1[2:]=100

In [32]:
arr1

array([  1,   2, 100, 100, 100, 100, 100, 100])

In [33]:
# this is called as broadcasting

In [35]:
new=arr1 (# sharing same memory locations)

In [37]:
new[3:]=500
new

array([  1,   2, 100, 500, 500, 500, 500, 500])

In [38]:
arr1

array([  1,   2, 100, 500, 500, 500, 500, 500])

We can see even we store arr1 in new, it is reference trpe and any changed in new will be 
reflected back in arr1 also

In [39]:
new=arr1.copy() # this reference type is overcome by copy function

In [40]:
print(arr1)
new[3:]=10
print(new)

[  1   2 100 500 500 500 500 500]
[  1   2 100  10  10  10  10  10]
