In [2]:

import pandas as pd
import numpy as np

In [4]:
a=pd.Series([1,2,3,4])
a


0    1
1    2
2    3
3    4
dtype: int64

In [9]:
a=pd.Series([11,12,1,3],index=[100,101,102,103])
a

100    11
101    12
102     1
103     3
dtype: int64

In [8]:
a=pd.Series([11,12,1,3],index=[100,101,102,103],dtype=float)  # we can change type of data
a

100    11.0
101    12.0
102     1.0
103     3.0
dtype: float64

In [11]:
s=pd.Series([10,20,30,40,50])
print(s[0])

10


In [12]:
s[0:3]

0    10
1    20
2    30
dtype: int64

In [15]:
# passing data from list
data=np.array([1,2,3,4,5])   # here i have creted a array
l1=[1,2,3,4]                # here also i have crerated a list which is like array 
print(c)   # in pandas series instead of passing the array directly we can pass the list or numpy arraydirectly
print(pd.Series(l1))


0    1
1    2
2    3
3    4
4    5
dtype: int32
0    1
1    2
2    3
3    4
dtype: int64


In [17]:
d2=np.array([1,2,3,4,5])   # METHOD 1
d1=np.array(l1)            #METHOD 2

# HERE ALSO PASSING THE LIST ON ARRAY INSTEAD OF SPECIFIYING IT DIRECTLY
print(d2)
print(d1)

[1 2 3 4 5]
[1 2 3 4]


In [21]:
 # pd.Series( in argument we can pass list,tuple,set,dictionary)
# EXAMPLE :
l1=[1,2,3,4,5]
#s1={1,2,3,4}
t1=(6,7,8,9)
dic1={'Name':'VIK','Age':29}
n1=np.array([5,1,6,7])

print(pd.Series(l1))
#print(pd.Series(s1))
print(pd.Series(t1))
print(pd.Series(dic1))
print(pd.Series(n1))

0    1
1    2
2    3
3    4
4    5
dtype: int64
0    6
1    7
2    8
3    9
dtype: int64
Name    VIK
Age      29
dtype: object
0    5
1    1
2    6
3    7
dtype: int32


# PANDAS DATAFRAME

DATAFRAME SHOULD HAVE ATLEAST 2 COLUMN AND AS MANY AS ROWS
AND SERIES HAVE ONLY ONE COLUMN AND AS MANY AS ROWS

In [24]:
import pandas as pd
 # pd.Series( in argument we can pass list,tuple,set,dictionary)
# EXAMPLE :
l1=[1,2,3,4,5]
t1=(6,7,8,9)
dic1={'Name':'VIK','Age':29}
n1=np.array([5,1,6,7])

print(pd.DataFrame(l1))
print(pd.DataFrame(t1))
print(pd.DataFrame(dic1))
print(pd.DataFrame(n1))


   0
0  1
1  2
2  3
3  4
4  5
   0
0  6
1  7
2  8
3  9


ValueError: If using all scalar values, you must pass an index

In [25]:
data=[1,2,3,4,5]
df=pd.DataFrame(data)   # data frame mai index ke sath ssab vertical form mai aata hai, aur isse pehel sab horizonal aata tha
df

0
0  1
1  2
2  3
3  4
4  5

In [28]:
data1=[['alexa',10],['Bob',12],['clarke',13]]   # list inside list
df=pd.DataFrame(data1)
df

0   1
0   alexa  10
1     Bob  12
2  clarke  13

In [30]:
data2=[['alexa',10],['bob',12],['clarke',19]]
df1=pd.DataFrame(data2,columns=['Name','Age'])
df1

Name  Age
0   alexa   10
1     bob   12
2  clarke   19

In [32]:
data2=[['alexa',10],['bob',12],['clarke',19]]
df2=pd.DataFrame(data2,columns=['Name','Age'],dtype=float)
df2 

# alexa and '10' in the first  the element decided that table has 2 columns

Name   Age
0   alexa  10.0
1     bob  12.0
2  clarke  19.0

In [33]:
data2={'Name':['Tom','jack','steve','ricky'],'Age':[28,29,34,21]}
df2=pd.DataFrame(data2)
df2

# first element in the data2 will decide the structure of the table


Name  Age
0    Tom   28
1   jack   29
2  steve   34
3  ricky   21

In [34]:
dat=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]
df=pd.DataFrame(dat)
df

# YAHA DAT KE BAAD COLUMNS NAME SPECIFY NAHI KRNA PADTA LIKE IN LIST


a   b     c
0  1   2   NaN
1  5  10  20.0

In [36]:
import pandas as pd
dat=[{'a':1,'b':2},{'a':5,'b':10,'c':20}]

df1=pd.DataFrame(dat,index=['first','second'])
df2=pd.DataFrame(dat,index=['first','second'],columns=['a1','b1'])
print(df1)
print("\n")
print(df2)

        a   b     c
first   1   2   NaN
second  5  10  20.0


        a1  b1
first  NaN NaN
second NaN NaN


In [3]:
import pandas as pd
data2=[[20,10],[10,12]]
df1=pd.DataFrame(data2)
df2=pd.DataFrame(data2)
df3=df2.append(df1)
df3

0   1
0  20  10
1  10  12
0  20  10
1  10  12

# I-LOC FUNCTION

It is like indexing in list and array
Indexing in dataframe is done by iloc( using index) and loc(using row/column name)


In [4]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(8,4),columns=['A','B','C','D'])
df

A         B         C         D
0 -0.093790 -0.101604 -0.729646 -1.300741
1 -0.576742  0.904230  0.436383  1.061379
2 -0.204244  0.447556  0.110421 -0.752228
3 -0.164225  0.706571 -0.045192 -1.340843
4 -0.454445  0.637139  0.630581  0.156862
5  1.193051  1.048687  1.737228  0.398062
6 -0.346127 -0.930494  1.315237 -0.530630
7 -0.798075  0.315470 -1.426572 -0.905548

In [41]:
df.iloc[0:4,0:2]   # iloc[row start: row end, column start:column end]
# iloc means indexing

A         B
0  0.697538  0.399854
1 -0.042220  0.510589
2  0.461140  0.521857
3 -0.094644 -1.015360

In [42]:
df.loc[:,'A':'C']    # we have to mention column name specifically

A         B         C
0  0.697538  0.399854  0.034954
1 -0.042220  0.510589 -0.251156
2  0.461140  0.521857  0.724086
3 -0.094644 -1.015360 -0.230113
4  1.788088  1.334236  0.634929
5  0.919970 -0.003381  1.295126
6  0.854739  0.952488  1.417052
7  0.233492  0.188116 -0.365688

In [7]:
df.loc['A']

KeyError: 'A'

In [11]:
df.iloc[0:-1,-2:-4]   # [0:-1] means all rows, [-2:-3]( -3 exclusive,
#means only -2 column

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

# DATA FRAME INTO ARRAYS

In [13]:
a=df.iloc[:,1:].values
print(a)

[[-0.10160361 -0.72964606 -1.3007411 ]
 [ 0.90423013  0.43638267  1.06137943]
 [ 0.44755646  0.11042115 -0.752228  ]
 [ 0.70657066 -0.0451916  -1.340843  ]
 [ 0.63713914  0.63058091  0.15686208]
 [ 1.04868652  1.7372284   0.39806195]
 [-0.93049384  1.31523658 -0.5306302 ]
 [ 0.31547004 -1.42657175 -0.9055478 ]]


In [14]:
type(a)

numpy.ndarray

In [1]:
import numpy as np
import pandas as pd
df=pd.DataFrame(np.random.randn(8,4),columns=['A','B','C','D'])
df

A         B         C         D
0 -0.479959  0.169578  1.478344  2.406689
1 -0.396931 -0.351725 -1.843561  0.173554
2 -1.255722  1.558119  0.090171  0.058586
3 -0.660173 -0.121617 -1.445608 -1.334439
4  0.506741  0.118895 -1.802869 -0.913254
5  0.060977  0.561588 -0.499319  1.045433
6 -0.462654  1.149011 -0.011993 -1.260508
7  0.540169 -2.066405 -0.265762 -0.783527

In [2]:
df['A']


0   -0.479959
1   -0.396931
2   -1.255722
3   -0.660173
4    0.506741
5    0.060977
6   -0.462654
7    0.540169
Name: A, dtype: float64

In [4]:
type(df['A']) #we know when we have only one column it is a series

pandas.core.series.Series

In [5]:
df[['A','B']]   # access multiple column

A         B
0 -0.479959  0.169578
1 -0.396931 -0.351725
2 -1.255722  1.558119
3 -0.660173 -0.121617
4  0.506741  0.118895
5  0.060977  0.561588
6 -0.462654  1.149011
7  0.540169 -2.066405

In [7]:
df['A','B']

KeyError: ('A', 'B')

In [ ]:
df=pd.read_csv() 
# agar file commas seperate hai toh sep',' by default rehta hai
# agar file koi aur sign se sepate kiya hai toh we have to write sep=';','&' isme se jo bhi symbol hai

DATAFRAME MAI ROWS SAARE SELECT HONE AGAR COL PAR KAAM HO RAHA HAI TOH
AGAR SPECIFIC ROW SELECT KRNA HAI TOH iloc function use krne padega

In [20]:
df[df['A']>0.1]  # it will select all the value in table where A>0.1

A         B         C         D
2  1.388955 -0.124895 -2.014014  0.817917
3  0.436006 -0.649291  1.216000 -0.920667
4  0.402037 -0.494560  0.645428 -1.610522
6  1.765450  0.866014  0.247873 -0.146427
7  1.243039  0.783678  0.885988 -1.824987

# CSV

In [ ]:
df=pd.read_csv('test.csv',usercols=['col1','col2'])  # while reading csv filw we can specify which all columns we wants explicitly

In [ ]:
df=pd.read_csv('test.csv',dtype=object) # all the data in the csv file will object(strings)

In [ ]:
df=pd.read_csv('test.csv',dtype=={'b':int,'c':float,'a':int64}) # all the data in the csv file will object(strings)

In [ ]:
pd.read_csv('test.csv',index_col=0)  # here we can make first column as index