In [1]:
l1=[1,2,3,4,6,7,8,9,10]
l2=list([21,25,34,76,98])

In [3]:
l2[1:5:2]

[25, 76]

In [4]:
l2[::-1]

[98, 76, 34, 25, 21]

In [7]:
l2.append(1)

In [8]:
l2

[98, 76, 34, 25, 21, 1, 1]

In [9]:
l2.insert(2,"1")

In [10]:
l2

[98, 76, '1', 34, 25, 21, 1, 1]

In [11]:
l2.insert(2,1)

In [12]:
l2

[98, 76, 1, '1', 34, 25, 21, 1, 1]

In [13]:
l2.pop()

1

In [14]:
l2

[98, 76, 1, '1', 34, 25, 21, 1]

In [15]:
l2.pop(1)

76

In [16]:
l2

[98, 1, '1', 34, 25, 21, 1]

In [17]:
l2.remove(98)

In [18]:
l2

[1, '1', 34, 25, 21, 1]

In [19]:
t=(1,2,3,4)

In [25]:
t

(1, 2, 3, 4)

In [21]:
t[0]

1

In [28]:
t

(1, 2, 3, 4)

In [29]:
t.remove(3)

AttributeError: 'tuple' object has no attribute 'remove'

In [30]:
dic={'col 1':"Vikas",'col 2':"Soni"}

In [31]:
dic


{'col 1': 'Vikas', 'col 2': 'Soni'}

In [33]:
dic['col 1']

'Vikas'

In [34]:
dic.values()

dict_values(['Vikas', 'Soni'])

In [36]:
dic.update({'col1 1':"Moni"})

In [37]:
dic

{'col 1': 'Vikas', 'col 2': 'Soni', 'col1 1': 'Moni'}

In [38]:
dic['col 1']="SURESH"

In [39]:
dic

{'col 1': 'SURESH', 'col 2': 'Soni', 'col1 1': 'Moni'}

In [40]:
dic={'Name':["vikas","soni","moni"],
     'sirname':["kumar","kumari","gupta"],
     'Age':[28,29,30]}

In [41]:
dic

{'Name': ['vikas', 'soni', 'moni'],
 'sirname': ['kumar', 'kumari', 'gupta'],
 'Age': [28, 29, 30]}

In [43]:
dic['Age']

[28, 29, 30]

In [46]:
dic.update({"Gender":['M','F','F']})

In [47]:
dic

{'Name': ['vikas', 'soni', 'moni'],
 'sirname': ['kumar', 'kumari', 'gupta'],
 'Age': [28, 29, 30],
 'Gender': ['M', 'F', 'F']}

In [49]:
for i in dic.values():
    print(i)

['vikas', 'soni', 'moni']
['kumar', 'kumari', 'gupta']
[28, 29, 30]
['M', 'F', 'F']


In [51]:
l1_dir()

NameError: name 'l1_dir' is not defined

In [54]:
a=[1,2,3,4]
b=set(a)

In [55]:
b

{1, 2, 3, 4}

In [57]:
def eve(num):
    if num%2==0:
        print("NUMBER IS EVEN")
    else:
        print("Number is odd")

In [58]:
num=input("enter the number")
eve(num)

enter the number5


TypeError: not all arguments converted during string formatting

In [59]:
def n(name,age):
    print("The name is {} and age is {}".format(name,age))

In [ ]:
def ind()

In [61]:
m=lambda a,b:a+b


In [62]:
m(12,13)

25

In [ ]:
l1=[1,2,3,4]
for i in l1:
    l1.append(i*i)
return l1

In [1]:
def odd(num):
    if num%2==0:
        return "The number is even"
    else:
        return "the number is odd"

In [7]:
l1=[1,2,3,4,5]
list(map(odd,l1))

['the number is odd',
 'The number is even',
 'the number is odd',
 'The number is even',
 'the number is odd']

In [6]:
new_lst=[i*i for i in l1 ]
new_lst

[1, 4, 9, 16, 25]

In [11]:
dic={'col1':"Vikas",'col2':"soni"}

In [12]:
dic

{'col1': 'Vikas', 'col2': 'soni'}

In [13]:
a=dict(dic)

In [14]:
a

{'col1': 'Vikas', 'col2': 'soni'}

In [15]:
a.update({'col3':"noni"})

In [16]:
a

{'col1': 'Vikas', 'col2': 'soni', 'col3': 'noni'}

In [17]:
import numpy as np

In [19]:
a=np.array([[1,2,3],[2,3,4]])

In [20]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [21]:
a=np.arange(10)

In [22]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
a=np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [29]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
import pandas as pd
a=pd.Series([1,2,3,4],index=[0,1,2,3])
a

0    1
1    2
2    3
3    4
dtype: int64

In [36]:
p=pd.DataFrame(l1,columns=['first'])
p

first
0      1
1      2
2      3
3      4
4      5

In [37]:
lis=[["vikas",28],['soni',30],['moni',56]]

In [39]:
a=pd.DataFrame(lis,columns=['Nmae','Age'])
a

Nmae  Age
0  vikas   28
1   soni   30
2   moni   56

In [53]:
di={'Name':['Vikas','soni','moni'],'SIRNAME':['Kumar','kumari','kumari'],'count':[1,2,3]}

In [65]:
s=pd.DataFrame(di,index=di['count'])
s

Name SIRNAME  count
1  Vikas   Kumar      1
2   soni  kumari      2
3   moni  kumari      3

In [70]:
z=pd.DataFrame(np.random.randn(8,4),columns=['A','B','C','D'])
z

A         B         C         D
0 -1.180913 -0.453200  0.553661 -0.629550
1 -0.550129 -0.887459 -0.392806  0.174748
2 -1.341728 -0.854602  0.295994 -0.686357
3 -0.355985 -0.837549 -0.688750 -0.407505
4  0.501901 -0.262521 -1.932696  0.147044
5 -2.281142  0.955045  0.370273 -1.657640
6  0.094142 -1.785931 -1.525584  0.743863
7 -0.385217  1.749899 -0.228656  0.119857

In [74]:
z[::]

A         B         C         D
0 -1.180913 -0.453200  0.553661 -0.629550
1 -0.550129 -0.887459 -0.392806  0.174748
2 -1.341728 -0.854602  0.295994 -0.686357
3 -0.355985 -0.837549 -0.688750 -0.407505
4  0.501901 -0.262521 -1.932696  0.147044
5 -2.281142  0.955045  0.370273 -1.657640
6  0.094142 -1.785931 -1.525584  0.743863
7 -0.385217  1.749899 -0.228656  0.119857

In [75]:
z.set_index('A')

B         C         D
A                                      
-1.180913 -0.453200  0.553661 -0.629550
-0.550129 -0.887459 -0.392806  0.174748
-1.341728 -0.854602  0.295994 -0.686357
-0.355985 -0.837549 -0.688750 -0.407505
 0.501901 -0.262521 -1.932696  0.147044
-2.281142  0.955045  0.370273 -1.657640
 0.094142 -1.785931 -1.525584  0.743863
-0.385217  1.749899 -0.228656  0.119857

In [2]:
class person:
    def __init__(self,name,age):
        self.name=name
        self.age=age
        
    
p1=person("vikas",28)

In [3]:
p1.name

'vikas'

In [4]:
p1=[1,2,3,5]

In [5]:
dir(p1)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__reversed__',
 '__rmul__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'append',
 'clear',
 'copy',
 'count',
 'extend',
 'index',
 'insert',
 'pop',
 'remove',
 'reverse',
 'sort']

In [ ]:
df.hist(x='Sex'y='age',data=df)